type Account {
    email: String! @unique
}

enum PaymentStatusOptions {
    cash
    paypal
    venmo
    card
    online
    unpaid
}

type Customer {
    shopifyCustomerId: String @unique
    name: String
    email: String
    phone: String
    acceptsMarketing: Boolean
    puttingLeaguePlayers: [PuttingLeaguePlayer] @relation
}


type PuttingLeagueTeam {
    players: [PuttingLeaguePlayer] @relation
    league: PuttingLeague
}

enum LeagueStatus {
    pending
    checkin
    active
    complete
}

type PuttingLeague {
    date: Date
    title: String
    productId: String @unique
    players: [PuttingLeaguePlayer] @relation
    teams: [PuttingLeagueTeam] @relation
    status: LeagueStatus
}

type PuttingLeaguePlayer {
    name: String
    league: PuttingLeague
    customer: Customer
    team: PuttingLeagueTeam
    payment: PaymentStatusOptions
    checkedIn: Boolean
    wins: Int
}

type Query {
    allPuttingLeagues: [PuttingLeague]
    allPuttingLeaguesByStatus(status: LeagueStatus): [PuttingLeague]
    allCustomers: [Customer]
    findLeagueByProductID(productId: String): PuttingLeague
}