type Account {
    email: String! @unique
}

enum PaymentStatusOptions {
    cash
    paypal
    venmo
    card
    online
    unpaid
}
type Player {
    firstName: String
    lastName: String
    email: String
    phone: String
    leagues: [LeaguePlayer] @relation
}

type Team {
    players: [LeaguePlayer] @relation
    league: League
}

type League {
    date: Date
    players: [LeaguePlayer] @relation
    teams: [Team] @relation
}

type LeaguePlayer {
    league: League
    player: Player
    team: Team
    payment: PaymentStatusOptions
    checkedIn: Boolean
    wins: Int
}

type Query {
    allLeagues: [League]
}